[project]
name = "verifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "db-models",
    "modifier",
]

[tool.uv.sources]
db-models = { workspace = true }
modifier = { workspace = true }
